import fs from 'fs'
import path from 'path'

const OUTPUTS_DIR = path.join(process.cwd(), 'content/poly-knowledge/outputs')

// Extended watchlist item with optional fields
export interface WatchlistItem {
  question: string
  score: number
  spread_pct: number | null
  liquidity: number | null
  days_to_event: number | null
  reason: string
  market_id?: string
  url?: string
  slug?: string
  endDate?: string
  end_date?: string
  negRisk?: boolean
  weather_signal_score?: number
  // Extended fields from task pipeline
  category?: string
  action?: string
  entry_plan?: string
  thesis?: string
  monitor_sources?: string[]
  key_risks?: string[]
  // Probability calculation fields (generated by task #40)
  assistant_prob?: number | null
  assistant_evidence?: {
    threshold?: number | null
    predicted_max?: number | null
    sigma?: number | null
    station?: string | null
    updated_at?: string | null
    market_price?: number | null
  }
}

export interface WatchlistData {
  date?: string
  generatedAt?: string
  generated_at?: string
  markets?: WatchlistItem[]
  watchlist?: (WatchlistItem & { rank?: number })[]
}

// Category detection keywords
const CATEGORY_KEYWORDS: Record<string, string[]> = {
  'weather': ['weather', 'snow', 'rain', 'temperature', 'storm', 'hurricane', 'wind', 'fog', 'precipitation', '天气', '降雪', '降雨', '温度', '风暴'],
  'aviation': ['flight', 'airline', 'airport', 'pilot', 'aviation', 'delay', '取消', '航班', '机场', '飞行员'],
  'macro': ['gdp', 'inflation', 'unemployment', 'interest rate', 'fed', 'recession', 'gdp', 'cpi', 'pce', '宏观', 'gdp', '通胀', '失业率'],
  'political': ['election', 'trump', 'biden', 'congress', 'senate', 'president', 'vote', 'policy', '选举', '总统', '国会', '投票'],
  'crypto': ['bitcoin', 'btc', 'ethereum', 'eth', 'solana', 'sol', 'crypto', '加密', '币'],
  'sports': ['nba', 'nfl', 'mlb', 'nhl', 'soccer', 'football', 'tennis', 'game', 'match', 'score', 'win', '联赛', '比赛', '得分'],
}

// Detect category from question/description if not provided
export function detectCategory(item: WatchlistItem): string {
  // Use existing category if available
  if (item.category && item.category !== 'unknown') {
    return item.category
  }

  const text = `${item.question} ${item.reason}`.toLowerCase()

  for (const [category, keywords] of Object.entries(CATEGORY_KEYWORDS)) {
    for (const keyword of keywords) {
      if (text.includes(keyword.toLowerCase())) {
        return category
      }
    }
  }

  return 'other'
}

// Get all available categories
export type FilterCategory = 'all' | 'weather' | 'aviation' | 'macro' | 'political' | 'crypto' | 'sports' | 'other'

export const FILTER_CATEGORIES: FilterCategory[] = ['all', 'weather', 'aviation', 'macro', 'political', 'crypto', 'sports', 'other']

// Category display names in Chinese
export const CATEGORY_LABELS: Record<FilterCategory, string> = {
  'all': '全部',
  'weather': '天气',
  'aviation': '航空',
  'macro': '宏观',
  'political': '政治',
  'crypto': 'Crypto',
  'sports': '体育',
  'other': '其它',
}

// Check if action is "consider" or "tracking"
export function isActionable(item: WatchlistItem): boolean {
  if (!item.action) return false
  const action = item.action.toLowerCase()
  return action.includes('考虑') || action.includes('跟踪') || action.includes('tracking') || action.includes('consider')
}

function normalizeWatchlistData(date: string, data: WatchlistData): { date: string; generatedAt: string; items: WatchlistItem[] } {
  const generatedAt = data.generatedAt || data.generated_at || new Date().toISOString()
  const items = (data.markets || data.watchlist || []).map((it: any) => {
    const scoreVal =
      typeof it.score === 'number'
        ? it.score
        : typeof it.scores?.total === 'number'
          ? it.scores.total
          : Number(it.score ?? 0)

    const spreadVal = typeof it.spread_pct === 'number' ? it.spread_pct : it.spread_pct == null ? null : Number(it.spread_pct)
    const liqVal = typeof it.liquidity === 'number' ? it.liquidity : it.liquidity == null ? null : Number(it.liquidity)
    const daysVal = typeof it.days_to_event === 'number' ? it.days_to_event : it.days_to_event == null ? null : Number(it.days_to_event)

    return {
      ...it,
      score: Number.isFinite(scoreVal) ? scoreVal : 0,
      spread_pct: Number.isFinite(spreadVal as any) ? (spreadVal as number) : null,
      liquidity: Number.isFinite(liqVal as any) ? (liqVal as number) : null,
      days_to_event: Number.isFinite(daysVal as any) ? (daysVal as number) : null,
      reason: it.reason || '',
      category: it.category,
      action: it.action,
      entry_plan: it.entry_plan,
      thesis: it.thesis,
      monitor_sources: it.monitor_sources,
      key_risks: it.key_risks,
      slug: it.slug,
      endDate: it.endDate || it.end_date,
      negRisk: it.negRisk,
      weather_signal_score: it.weather_signal_score,
      // Probability calculation fields (generated by task #40)
      assistant_prob: it.assistant_prob ?? null,
      assistant_evidence: it.assistant_evidence ? {
        threshold: it.assistant_evidence.threshold ?? null,
        predicted_max: it.assistant_evidence.predicted_max ?? null,
        sigma: it.assistant_evidence.sigma ?? null,
        station: it.assistant_evidence.station ?? null,
        updated_at: it.assistant_evidence.updated_at ?? null,
        market_price: it.assistant_evidence.market_price ?? null,
      } : undefined,
    } as WatchlistItem
  })
  return { date, generatedAt, items }
}

/**
 * Get all watchlist files sorted by date (newest first).
 */
export function getAllWatchlistFiles(): string[] {
  if (!fs.existsSync(OUTPUTS_DIR)) {
    return []
  }

  const files = fs.readdirSync(OUTPUTS_DIR)
  const watchlistFiles = files
    .filter((f) => f.match(/^watchlist-\d{4}-\d{2}-\d{2}\.json$/))
    .map((f) => path.join(OUTPUTS_DIR, f))
    .sort()
    .reverse()

  return watchlistFiles
}

/**
 * Get the latest watchlist file path.
 */
export function getLatestWatchlistPath(): string | null {
  const files = getAllWatchlistFiles()
  return files.length > 0 ? files[0] : null
}

/**
 * Get the latest watchlist date string (YYYY-MM-DD).
 */
export function getLatestWatchlistDate(): string | null {
  const latestPath = getLatestWatchlistPath()
  if (!latestPath) return null

  const match = path.basename(latestPath).match(/watchlist-(\d{4}-\d{2}-\d{2})\.json/)
  return match ? match[1] : null
}

/**
 * Read and parse a watchlist file by date.
 */
export function getWatchlistByDate(date: string): { date: string; generatedAt: string; items: WatchlistItem[] } | null {
  const filePath = path.join(OUTPUTS_DIR, `watchlist-${date}.json`)

  if (!fs.existsSync(filePath)) return null

  try {
    const raw = fs.readFileSync(filePath, 'utf-8')
    const data = JSON.parse(raw) as WatchlistData
    return normalizeWatchlistData(date, data)
  } catch (error) {
    console.error(`Error parsing watchlist ${date}:`, error)
    return null
  }
}

/**
 * Get the latest watchlist data.
 */
export function getLatestWatchlist(): { date: string; generatedAt: string; items: WatchlistItem[] } | null {
  const latestDate = getLatestWatchlistDate()
  if (!latestDate) return null
  return getWatchlistByDate(latestDate)
}

/**
 * Get watchlist items with optional limit.
 */
export function getWatchlistItems(date: string, limit?: number): WatchlistItem[] {
  const data = getWatchlistByDate(date)
  if (!data) return []

  const items = [...data.items].sort((a, b) => b.score - a.score)
  return limit ? items.slice(0, limit) : items
}

/**
 * Get latest watchlist items with optional limit.
 */
export function getLatestWatchlistItems(limit: number = 20): WatchlistItem[] {
  const data = getLatestWatchlist()
  if (!data) return []

  const items = [...data.items].sort((a, b) => b.score - a.score)
  return items.slice(0, limit)
}

/**
 * Get weather/aviation actionable items (action = consider/track)
 * Fallback: if no actionable items, return top weather/aviation items with warning
 */
export function getWeatherActionItems(limit: number = 5): WatchlistItem[] {
  const data = getLatestWatchlist()
  if (!data) return []

  // First try to get actionable items (consider/track)
  const weatherAviationItems = data.items.filter(item => {
    const category = detectCategory(item)
    return (category === 'weather' || category === 'aviation') && isActionable(item)
  })

  // If we have actionable items, return them
  if (weatherAviationItems.length > 0) {
    return weatherAviationItems
      .sort((a, b) => b.score - a.score)
      .slice(0, limit)
  }

  // Fallback: if no actionable items, get all weather/aviation items
  // This handles the case where all weather items have action="跳过/观察"
  const allWeatherAviationItems = data.items.filter(item => {
    const category = detectCategory(item)
    return category === 'weather' || category === 'aviation'
  })

  return allWeatherAviationItems
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
}

/**
 * Get items filtered by category
 */
export function getFilteredWatchlistItems(category: FilterCategory, limit?: number): WatchlistItem[] {
  const data = getLatestWatchlist()
  if (!data) return []

  let items = data.items

  if (category !== 'all') {
    items = items.filter(item => detectCategory(item) === category)
  }

  items = [...items].sort((a, b) => b.score - a.score)
  return limit ? items.slice(0, limit) : items
}
